Zoo: Fix non-pretrained U-Net Model disconnected vertex and output activation function
When using UNet without the pretrained model, one receives the error:

```
java.lang.IllegalStateException: Invalid configuration: disconnected vertices
found - [up9-1]. Disconnected vertices are those that do not connect to either
another vertex, and are also not a network output. To disable this error (i.e.,
allow network configurations with disconnected vertices) use GraphBuilder.allowDisconnected(true)

	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.validate(ComputationGraphConfiguration.java:347)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:1036)
	at org.deeplearning4j.zoo.model.UNet.init(UNet.java:93)
	at org.deeplearning4j.zoo.model.UNet.init(UNet.java:51)
```

Example test code:

```
ZooModel zooModel = UNet.builder().build();
zooModel.init();
```

Fix by connecting disconnected up9-1 vertex

Then, we receive the error
```
org.deeplearning4j.exception.DL4JInvalidConfigException: Invalid output layer
configuration for layer "output": sigmoid activation function in combination
with LossMCXENT (multi-class cross entropy loss function). For multi-class
classification, use softmax + MCXENT (multi-class cross entropy);
for binary multi-label classification, use sigmoid + XENT.

This configuration validation check can be disabled for
MultiLayerConfiguration and ComputationGraphConfiguration using validateOutputLayerConfig(false), however this is not recommended.
```

Fix by changing output activation to Activation.SOFTMAX instead of default sigmoid