Zoo: Fix U-Net disconnected vertex and output activation function, fix VGG16, add test (#6653)
* Zoo: Fix non-pretrained U-Net Model disconnected vertex and output activation function

When using UNet without the pretrained model, one receives the error:

```
java.lang.IllegalStateException: Invalid configuration: disconnected vertices
found - [up9-1]. Disconnected vertices are those that do not connect to either
another vertex, and are also not a network output. To disable this error (i.e.,
allow network configurations with disconnected vertices) use GraphBuilder.allowDisconnected(true)

	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration.validate(ComputationGraphConfiguration.java:347)
	at org.deeplearning4j.nn.conf.ComputationGraphConfiguration$GraphBuilder.build(ComputationGraphConfiguration.java:1036)
	at org.deeplearning4j.zoo.model.UNet.init(UNet.java:93)
	at org.deeplearning4j.zoo.model.UNet.init(UNet.java:51)
```

Example test code:

```
ZooModel zooModel = UNet.builder().build();
zooModel.init();
```

Fix by connecting disconnected up9-1 vertex

Then, we receive the error
```
org.deeplearning4j.exception.DL4JInvalidConfigException: Invalid output layer
configuration for layer "output": sigmoid activation function in combination
with LossMCXENT (multi-class cross entropy loss function). For multi-class
classification, use softmax + MCXENT (multi-class cross entropy);
for binary multi-label classification, use sigmoid + XENT.

This configuration validation check can be disabled for
MultiLayerConfiguration and ComputationGraphConfiguration using validateOutputLayerConfig(false), however this is not recommended.
```

Fix by changing output activation to Activation.SOFTMAX instead of default sigmoid

* Zoo: Fix VGG16 non-pretrained model and add UNet to testInitNotPretrained

* Zoo: Keep input and output sizes the same for U-Net to avoid error in backpropagation (graph doesn't appear to support truncation

```
If you input both labels and input as 128x128, you get:

java.lang.IllegalArgumentException: Labels and preOutput must have equal shapes: got shapes [16384, 1] vs [15876, 1]

	at org.nd4j.base.Preconditions.throwEx(Preconditions.java:621)
	at org.nd4j.linalg.lossfunctions.impl.LossMCXENT.computeGradient(LossMCXENT.java:155)
	at org.deeplearning4j.nn.layers.convolution.CnnLossLayer.backpropGradient(CnnLossLayer.java:84)
	at org.deeplearning4j.nn.graph.vertex.impl.LayerVertex.doBackward(LayerVertex.java:148)
	at org.deeplearning4j.nn.graph.ComputationGraph.calcBackpropGradients(ComputationGraph.java:2592)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1366)
	at org.deeplearning4j.nn.graph.ComputationGraph.computeGradientAndScore(ComputationGraph.java:1326)
	at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:160)
	at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:51)
	at org.deeplearning4j.optimize.Solver.optimize(Solver.java:52)
	at org.deeplearning4j.nn.graph.ComputationGraph.fitHelper(ComputationGraph.java:1149)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1098)
	at org.deeplearning4j.nn.graph.ComputationGraph.fit(ComputationGraph.java:1085)
```